name: vuepress-deploy

on:
  push:
    branches: [ dev-web]
  pull_request:
    branches: [ dev-web ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        TARGET_REPO: KimYangOfCat/2021-CSPostgraduate-408
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: Notes/.vuepress/dist/
